List=[1,23,56,8,9,10,56,89,45]
List.sort()
print("The sorted list is: ",List)
List.reverse()
print("The reverse of a list is ",List)
List.append(15)
print("The list after append is ",List)
List.insert(3,30)
print("list after insertion of element at index 3 is: ",List)
List.pop(2)
print("List after popping an element at index 2 is: ",List)
List.remove(8)
print("list after removing an element is: ",List)
